### ISSUE TITLE
Prefix tree should commit to sets of versions

### ISSUE THREAD

**Issue by felixlinker** [Bren2010/draft-keytrans#5]
Currently, the prefix tree commits to one key-version pair per leaf. I would argue that the leafs should commit to lists of key-version pairs (as the Merkle^2 paper suggests). This way, users can more easily monitor that the server did not include a fake key before to the current epoch.

**Comment by Bren2010** [comment]
I'm not sure there's any security benefit to having multiple key-version pairs per leaf. It makes things more complicated though, because you have to add an extra step where you are digging into the multiple changes that happened at that one leaf

**Comment by felixlinker** [comment]
Brendan and I clarified this issue in a call. My understanding of which indices are used in the prefix tree was wrong.
